name: Deploy to Production
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  deploy-production:
    name: Deploy production
    uses: AplinkosMinisterija/reusable-workflows/.github/workflows/biip-deploy.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      environment: Production
      docker-image: ghcr.io/AplinkosMinisterija/biip-uetk-web
      build-args: |
        NODE_ENV=production
        VITE_SENTRY_ENV=production
        VITE_SENTRY_DSN=https://e2494aceced346f6b08c57e7ec8769ae@sentry.biip.lt/12
        VITE_MAPS_HOST=https://maps.biip.lt
        VITE_BASE_URL=/app
